# Generated by Django 5.0.2 on 2024-05-06 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CGMInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField()),
                ('fallnumber', models.CharField(max_length=20)),
                ('changed_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
