# Generated by Django 5.0.2 on 2024-03-03 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='gender',
        ),
    ]
