# Generated by Django 5.0.2 on 2024-03-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_questions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='input_text',
            new_name='question_text',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='input_area',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='input_bool',
        ),
        migrations.AlterField(
            model_name='questions',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
