# Generated by Django 5.0.2 on 2024-04-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_answertemplatequestions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answertemplatequestions',
            name='answer_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
