# Generated by Django 5.0.2 on 2024-04-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_answertemplatequestions_answer_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_sms_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='mobile_number',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='sms_time_for_valid',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='verification_code',
            field=models.CharField(default=2, max_length=6),
            preserve_default=False,
        ),
    ]
