# Generated by Django 5.0.2 on 2024-04-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_patient_is_email_verified_patient_is_sms_verified_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='verification_code',
            new_name='verification_email_code',
        ),
        migrations.AddField(
            model_name='patient',
            name='verification_sms_code',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
    ]
