# Generated by Django 5.0.2 on 2024-04-30 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_verification_code_patient_verification_email_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='verification_email_code',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='patient',
            name='verification_sms_code',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
