# Generated by Django 5.0.2 on 2024-05-03 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_patient_verification_email_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='prerequisite',
        ),
        migrations.DeleteModel(
            name='AnswerTemplateQuestions',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
    ]
