# Generated by Django 5.0.2 on 2024-05-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='CGMInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField()),
                ('fallnumber', models.CharField(max_length=20)),
            ],
        ),
    ]
