# Generated by Django 5.0.2 on 2024-05-06 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_cgminput_changed_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CGMInput',
        ),
    ]
