# Generated by Django 5.0.2 on 2024-05-03 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinet_patient_form', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignedrule',
            name='role',
        ),
        migrations.RemoveField(
            model_name='assignedrule',
            name='user',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='AssignedRule',
        ),
    ]
